.

diff --git a/users/manuel/EndeavourOS-ISO/airootfs/usr/bin/create-ml b/users/manuel/EndeavourOS-ISO/airootfs/usr/bin/create-ml
--- a/users/manuel/EndeavourOS-ISO/airootfs/usr/bin/create-ml
+++ b/users/manuel/EndeavourOS-ISO/airootfs/usr/bin/create-ml
@@ -2,7 +2,7 @@
 
 echo2()  { echo -e "$@" >&2; }
 WARN()   { echo2 "==> $progname: warning: $1"; }
-DIE()    { echo2 "==> $progname: error: $1"; exit 1; }
+DIE()    { Cleanup; echo2 "==> $progname: error: $1"; exit 1; }
 ASSERT() { "$@" || DIE "'$*' failed."; }
 
 FetchMirrors() {
@@ -70,17 +70,27 @@ ExtractCountryMirrors() {
 
 HandleCountry() {
     local cc="$1"
-    local countries_handled=()
-    if printf "%s\n" "${countries_handled[@]}" | grep "$cc" >/dev/null ; then
+    [ "$cc" ] || return
+    local cn=${reflector_countries[$cc]}
+    if [ -z "$cn" ] ; then
+        WARN "'$cc': no active Arch mirrors found for this country"
+        return
+    fi
+    if printf "%s\n" "${countries_handled[@]}" | grep "^$cc$" >/dev/null ; then
         return
     else
+        echo2 "==> including mirrors from $cn"
         countries_handled+=("$cc")
-        local cn=$(CC2name $cc)
-        if [ "$cn" ] ; then
-            ExtractCountryMirrors "$cn" >> "$tmplist"
-        else
-            WARN "'$arg': no active Arch mirrors found for this country"
-        fi
+        ExtractCountryMirrors "$cn" >> "$tmplist"
+    fi
+}
+
+Cleanup() {
+    if [ "$cleanups" ] ; then
+        local cmd
+        for cmd in "${cleanups[@]}" ; do
+            $cmd
+        done
     fi
 }
 
@@ -88,19 +98,21 @@ Parameters() {
     local arg
     for arg in "$@" ; do
         case "$arg" in
-            --no-local)        local_country=no ;;
+            --nolocal)         local_country=no ;;
             --http | --rsync)  protocols+=(${arg:2}) ;;
             --sequential)      parallel=no ;;
             --update)          rm -f $mirrordata $dbfile ;;
             --nosave)          save=no ;;
+            -v | --verbose)    verbose=yes ;;
             -h | --help)
                 cat <<EOF >&2
 Usage:   $progname [options]
 Options: -h, --help    This help.
-         --no-local    Do not include mirrors from the current country.
+         --nolocal     Do not include mirrors from the current country.
          --sequential  Rank mirrors sequentially (slower) instead of in parallel (faster).
          --update      Update support data files that will be stored in the ISO.
          --nosave      Do not save mirrorlist to $target.
+         -v, --verbose Show more ranking details.
          --http        Include mirrors with http://
          --rsync       Include mirrors with rsync://
 Mirrors with https:// are included by default.
@@ -113,18 +125,20 @@ EOF
     done
 }
 
-Main() {
+Main2() {
     local -r progname=${0##*/}
     local -r active_mirrors_url=https://archlinux.org/mirrorlist/all     # mirrors active at the time listed in the file, both https and http
     local -r mirrordata=arch-mirrors-active                              # support file: active Arch mirrors in various countries
     local -r dbfile=arch-countries                                       # support file: mappings between country-code and country-name
 
+    local verbose=no
     local save=yes
     local generation_phase=no                                            # generating support files or not?
     local parallel=yes                                                   # ranking mirrors in pararallel or not?
     local local_country=yes                                              # include local country in the mirrorlist or not?
     local protocols=(https)                                              # list of supported protocols
     local countries_given=()                                             # list of user given countries which have mirrors to include
+    local countries_handled=()
     local target=/etc/pacman.d/mirrorlist
     local cleanups=()
 
@@ -146,10 +160,11 @@ Main() {
     local tmplist=$(mktemp)                           # collect mirrors that user wanted here
     local mirrorlist=$(mktemp)
 
-    cleanups+=($tmplist)
-    [ $save = yes ] && cleanups+=($mirrorlist)
+    chmod go-rwx $tmplist $mirrorlist
+    cleanups+=("rm -f '$tmplist'"
+               "rm -f '$mirrorlist'")
 
-    chmod go-rwx $tmplist
+    local arg argl                                    # argl = $arg with lower case letters
 
     # if user wanted, add the current country into $tmplist
     if [ $local_country = yes ] ; then
@@ -158,7 +173,6 @@ Main() {
     fi
 
     # add user given countries into $tmplist
-    local arg argl                                    # = $arg with lower case letters
     for arg in "${countries_given[@]}" ; do
         argl=${arg,,}
         case "$argl" in
@@ -167,16 +181,16 @@ Main() {
         esac
     done
 
-    local opt="-v"
-    case "$parallel" in
-        yes) opt+="p" ;;
-    esac
+    local opt=()
+    [ $verbose  = yes ] && opt+=(-v)
+    [ $parallel = yes ] && opt+=(-p)
+
     echo2 "==> Ranking mirrors."
     {
-        echo -e "### Mirror list generated by $progname at $(date "+%Y-%m-%d %X")"
+        echo -e "### Mirror list generated at $(date "+%Y-%m-%d %X")"
         echo -e "### Command: $progname $*\n"
-        ./rankmirrors-arch $opt $tmplist | column -t -s'|'
-    } | tee $mirrorlist
+        ./rankmirrors-arch "${opt[@]}" $tmplist | column -t -s'|'
+    } > $mirrorlist
     echo2 "==> Mirrors ranked."
 
     if [ $save = yes ] ; then
@@ -186,14 +200,32 @@ Main() {
         sudo cp -iv $mirrorlist $target
         sudo chmod go+r $target
     else
-        # less $mirrorlist
-        echo2 "==> $target not updated."
+        cat $mirrorlist
+        echo2 "\n==> $target NOT updated because of option --nosave."
     fi
     Cleanup
 }
 
-Cleanup() {
-    [ "$cleanups" ] && rm -f "${cleanups[@]}"
+Main() {
+    local args=() arg cc
+    for arg in "$@" ; do
+        case "$arg" in
+            -r | --recommended-countries)
+                cc=$(show-location-info --tolower country)
+                case "$cc" in
+                    au|de|us|cn) ;;
+                    ca|mx|br)    args+=(ww us) ;;
+                    fr|gb|pl|es) args+=(ww de) ;;
+                    "fi")        args+=(ww se de) ;;
+                    *)           args+=(ww de us) ;;
+                esac
+                ;;
+            *)
+                args+=("$arg")
+                ;;
+        esac
+    done
+    Main2 "${args[@]}"
 }
 
 Main "$@"
